eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      default-zone: ${EUREKA_SERVER:http://localhost:8761/eureka}

secured:
  app:
    uri: /accounts/api/v1/auth/**
    header: Authorization
    prefix: Bearer 
    jwtSecret: SecuredSecretKeyabracadabrajide05
    jwtExpirationMs: 86400000

  