eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      default-zone: http://172.31.12.219:8761/eureka

secured:
  app:
    uri: /accounts/api/v1/auth/**
    header: Authorization
    prefix: Bearer 
    jwtSecret: SecuredSecretKeyabracadabrajide05
    jwtExpirationMs: 86400000

  